#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 120000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "rGgYQ/rbaq74"
#define LAYER_STATE_8BIT

#define NAVIGATOR_TRACKBALL_CPI 30
#define NAVIGATOR_SCROLL_DIVIDER 50

#define NAVIGATOR_SCROLL_INVERT_X
#define NAVIGATOR_SCROLL_INVERT_Y
#define AUTOMOUSE_LAYER 1
#define AUTOMOUSE_TIMEOUT 200
#define AUTOMOUSE_THRESHOLD 10
#define AUTOMOUSE_ONESHOT
#define AUTOMOUSE_SCROLL_THRESHOLD AUTOMOUSE_THRESHOLD / NAVIGATOR_SCROLL_DIVIDER
#define RGB_MATRIX_STARTUP_SPD 60

